services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mail.privateemail.com:587
      - GF_SMTP_USER=email@example.com #enda email
      - GF_SMTP_PASSWORD=password # enda parool
      - GF_SMTP_FROM_ADDRESS=email@example.com # enda email
      - GF_SMTP_FROM_NAME=Grafana
  ntopng:
    image: ntop/ntopng:latest
    ports:
      - "3001:3000"
    environment:
      - NTOPNG_USER=admin
  labdash:
    container_name: lab-dash
    image: ghcr.io/anthonygress/lab-dash:latest
    privileged: true
    ports:
      - "2022:2022"
          environment:
      - SECRET=YOUR_SECRET_KEY  # Asenda see juhusliku stringiga JWT krüptimiseks
    volumes:
      - /sys:/sys:ro
      - ./labdash-config:/config
      - ./labdash-uploads:/app/public/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  pihole:
    image: pihole/pihole:latest
#    network_mode: host
    networks:
      macvlan:
        ipv4_address: 192.168.4.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
    hostname: pihole
    environment:
        environment:
 #     - DNS1=8.8.8.8
 #     - DNS2=8.8.4.4
      DHCP_ENABLED: 'true'
      DHCP_INTERFACE: 'enp2s0'
      WEBPASSWORD: 'parool' #kasuta enda parooli
      TZ: 'Europe/Tallinn'
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    ports:
          - "9617:9617/tcp"
    environment:
      PIHOLE_HOSTNAME: "home-server-pihole-1"
      PIHOLE_PASSWORD: "parool" # Kasuta enda parooli
volumes:
  grafana-data:
  pihole_data:
  dnsmasq_data:
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.4.0/24
