global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "pihole"
    static_configs:
      - targets: ["ip-address:9617"] # asendada enda pihole exporter ip-ga
